name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_PEM }}" > deploy_key.pem
          chmod 400 deploy_key.pem

      - name: Deploy to server
        run: |
          # SSH to the server and run deploy commands
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_IP }} << EOF
            # Login to GitHub Container Registry
            echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            # Pull the latest Docker image
            docker pull ghcr.io/${{ github.repository }}:latest

            # Stop and remove the existing container if it's running
            docker stop xalosserver-web || true
            docker rm xalosserver-web || true

            # Run the new container
            docker run -d \
              --name xalosserver-web \
              -p 80:80 \
              --restart unless-stopped \
              ghcr.io/${{ github.repository }}:latest

            # Remove unused images to free up space
            docker image prune -f
          EOF
